[Service]
ExecStart=
ExecStart=/usr/sbin/readsb \
  --device-type=rtlsdr --device=0 --freq=1090000000 --gain=auto \
  --write-json=/mnt/SYSTEM_ARCHIVE/OBSERVATORY/runtime/readsb \
  --write-json-every=1 --json-location-accuracy=2 \
  --net \
  --net-bind-address 0.0.0.0 \
  --net-ro-port 30002 \
  --net-sbs-port 30003 \
  --net-bo-port 30005 \
  --lat 46.603109 --lon -112.014606 \
                --net-json-port 30007 \
                --net-json-port-wind-triggered

